### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by pchaganti** [y13i/sgviz#2]
This is a nice tool to view security groups in a VPC. Noticed that the TODO mentions adding various other VPC resources to the map. Would you be interested in extending this into something more comprehensive? 

thanks

**Comment by y13i** [comment]
@pchaganti 
I'm very sorry for replying so late.

I appreciate for commenting on and using this!

I want to extend and get more quality (such as test codes, etc.) to this gem.
But I'm too busy to spend a time with this due to other work for now.

Thank you.

**Comment by pchaganti** [comment]
No worries. Thx!
